Adds fedora testing

diff --git a/vendor/bats-core/libexec/bats-core/bats b/vendor/bats-core/libexec/bats-core/bats
--- a/vendor/bats-core/libexec/bats-core/bats
+++ b/vendor/bats-core/libexec/bats-core/bats
@@ -1,13 +1,11 @@
 #!/usr/bin/env bash
 set -e
 
-version() {
-  printf 'Bats 1.1.0\n'
-}
+export BATS_VERSION='1.3.0'
+VALID_FORMATTERS="pretty, junit, tap, tap13"
 
-usage() {
-  version
-  printf 'Usage: bats [-c] [-r] [-p | -t] <test> [<test> ...]\n'
+version() {
+  printf 'Bats %s\n' "$BATS_VERSION"
 }
 
 abort() {
@@ -16,26 +14,43 @@ abort() {
   exit 1
 }
 
-help() {
+usage() {
+  local cmd="${0##*/}"
   local line
-  usage
-  while read -r line; do
-    printf '%s\n' "$line"
-  done <<END_OF_HELP_TEXT
 
-  <test> is the path to a Bats test file, or the path to a directory
-  containing Bats test files.
+  cat <<HELP_TEXT_HEADER
+Usage: ${cmd} [OPTIONS] <tests>
+       ${cmd} [-h | -v]
 
-  -c, --count      Count the number of test cases without running any tests
-  -h, --help       Display this help message
-  -p, --pretty     Show results in pretty format (default for terminals)
-  -r, --recursive  Include tests in subdirectories
-  -t, --tap        Show results in TAP format
-  -v, --version    Display the version number
+HELP_TEXT_HEADER
+
+  cat <<'HELP_TEXT_BODY'
+  <tests> is the path to a Bats test file, or the path to a directory
+  containing Bats test files (ending with ".bats")
+
+  -c, --count               Count test cases without running any tests
+  -f, --filter <regex>      Only run tests that match the regular expression
+  -F, --formatter <type>    Switch between formatters: pretty (default),
+                              tap (default w/o term), tap13, junit
+  -h, --help                Display this help message
+  -j, --jobs <jobs>         Number of parallel jobs (requires GNU parallel)
+  --no-tempdir-cleanup      Preserve test output temporary directory
+  --no-parallelize-across-files
+                            Serialize test file execution instead of running
+                            them in parallel (requires --jobs >1)
+  --no-parallelize-within-files
+                            Serialize test execution within files instead of
+                            running them in parallel (requires --jobs >1)
+  --report-formatter <type> Switch between reporters (same options as --formatter)
+  -o, --output <dir>        Directory to write report files
+  -p, --pretty              Shorthand for "--formatter pretty"
+  -r, --recursive           Include tests in subdirectories
+  -t, --tap                 Shorthand for "--formatter tap"
+  -T, --timing              Add timing information to tests
+  -v, --version             Display the version number
 
   For more information, see https://github.com/bats-core/bats-core
-
-END_OF_HELP_TEXT
+HELP_TEXT_BODY
 }
 
 expand_path() {
@@ -53,71 +68,197 @@ expand_path() {
   printf -v "$result" '%s/%s' "$dirname" "${path##*/}"
 }
 
+BATS_LIBEXEC="$(dirname "$(bats_readlinkf "${BASH_SOURCE[0]}")")"
+export BATS_LIBEXEC
 export BATS_CWD="$PWD"
 export BATS_TEST_PATTERN="^[[:blank:]]*@test[[:blank:]]+(.*[^[:blank:]])[[:blank:]]+\{(.*)\$"
-export PATH="$BATS_ROOT/libexec/bats-core:$PATH"
+export BATS_TEST_PATTERN_COMMENT="[[:blank:]]*([^[:blank:]()]+)[[:blank:]]*\(?\)?[[:blank:]]+\{[[:blank:]]+#[[:blank:]]*@test[[:blank:]]*\$"
+export BATS_TEST_FILTER=
+export PATH="$BATS_LIBEXEC:$PATH"
+export BATS_ROOT_PID=$$
+if [[ -z "${TMPDIR-}" ]]; then
+  export BATS_TMPDIR="/tmp"
+else
+  export BATS_TMPDIR="${TMPDIR%/}"
+fi
+export BATS_RUN_TMPDIR="$BATS_TMPDIR/bats-run-$BATS_ROOT_PID"
 
-options=()
 arguments=()
+
+# Unpack single-character options bundled together, e.g. -cr, -pr.
 for arg in "$@"; do
-  if [[ "${arg:0:1}" = "-" ]]; then
-    if [[ "${arg:1:1}" = "-" ]]; then
-      options[${#options[*]}]="${arg:2}"
-    else
-      index=1
-      while option="${arg:$index:1}"; do
-        if [[ -z "$option" ]]; then
-          break
-        fi
-        options[${#options[*]}]="$option"
-        let index+=1
-      done
-    fi
+  if [[ "$arg" =~ ^-[^-]. ]]; then
+    index=1
+    while option="${arg:$((index++)):1}"; do
+      if [[ -z "$option" ]]; then
+        break
+      fi
+      arguments+=("-$option")
+    done
   else
-    arguments[${#arguments[*]}]="$arg"
+    arguments+=("$arg")
   fi
+  shift
 done
 
-unset count_flag pretty recursive
-count_flag=''
-pretty=''
-recursive=''
-if [[ -z "${CI:-}" && -t 0 && -t 1 ]]; then
-  pretty=1
+set -- "${arguments[@]}"
+arguments=()
+
+unset flags recursive formatter_flags
+flags=('--dummy-flag') # add a dummy flag to prevent unset varialeb errors on empty array expansion in old bash versions
+formatter_flags=('--dummy-flag') # add a dummy flag to prevent unset varialeb errors on empty array expansion in old bash versions
+formatter='tap'
+report_formatter=''
+recursive=
+export BATS_TEMPDIR_CLEANUP=1
+output=
+if [[ -z "${CI:-}" && -t 0 && -t 1 ]] && command -v tput >/dev/null; then
+  formatter='pretty'
 fi
 
-if [[ "${#options[@]}" -ne 0 ]]; then
-  for option in "${options[@]}"; do
-    case "$option" in
-    "h" | "help" )
-      help
-      exit 0
-      ;;
-    "v" | "version" )
-      version
-      exit 0
-      ;;
-    "c" | "count" )
-      count_flag="-c"
-      ;;
-    "r" | "recursive" )
-      recursive=1
-      ;;
-    "t" | "tap" )
-      pretty=""
-      ;;
-    "p" | "pretty" )
-      pretty=1
-      ;;
-    * )
-      abort "Bad command line option '-$option'"
-      ;;
-    esac
-  done
+while [[ "$#" -ne 0 ]]; do
+  case "$1" in
+  -h | --help)
+    version
+    usage
+    exit 0
+    ;;
+  -v | --version)
+    version
+    exit 0
+    ;;
+  -c | --count)
+    flags+=('-c')
+    ;;
+  -f | --filter)
+    shift
+    flags+=('-f' "$1")
+    ;;
+  -F | --formatter)
+    shift
+    # allow cat formatter to see extended output but don't advertise to users
+    if [[ $1 =~ ^(pretty|junit|tap|tap13|cat)$ ]]; then
+      formatter="$1"
+    else
+      printf "Unknown formatter '%s', valid options are %s\n" "$1" "${VALID_FORMATTERS}"
+      exit 1
+    fi
+    ;;
+  --report-formatter)
+    shift
+    if [[ $1 =~ ^(pretty|junit|tap|tap13)$ ]]; then
+      report_formatter="$1"
+    else
+      printf "Unknown report formatter '%s', valid options are %s\n" "$1" "${VALID_FORMATTERS}"
+      exit 1
+    fi
+    ;;
+  -o | --output)
+    shift
+    output="$1"
+    ;;
+  -p | --pretty)
+    formatter='pretty'
+    ;;
+  -j | --jobs)
+    shift
+    flags+=('-j' "$1")
+    ;;
+  -r | --recursive)
+    recursive=1
+    ;;
+  -t | --tap)
+    formatter='tap'
+    ;;
+  -T | --timing)
+    flags+=('-T')
+    formatter_flags+=('-T')
+    ;;
+  # this flag is now a no-op, as it is the parallel default
+  --parallel-preserve-environment)
+    ;;
+  --no-parallelize-across-files)
+    flags+=("--no-parallelize-across-files")
+    ;;
+  --no-parallelize-within-files)
+    flags+=("--no-parallelize-within-files")
+    ;;
+  --no-tempdir-cleanup)
+    BATS_TEMPDIR_CLEANUP=''
+    ;;
+  --tempdir) # for internal test consumption only!
+    BATS_RUN_TMPDIR="$2"
+    shift
+    ;;
+  -*)
+    abort "Bad command line option '$1'"
+    ;;
+  *)
+    arguments+=("$1")
+    ;;
+  esac
+  shift
+done
+
+if [[ -d "$BATS_RUN_TMPDIR" ]]; then
+  printf "Error: BATS_RUN_TMPDIR (%s) already exists\n" "$BATS_RUN_TMPDIR" >&2
+  printf "Reusing old run directories can lead to unexpected results ... aborting!\n" >&2
+  exit 1
+fi
+mkdir -p "$BATS_RUN_TMPDIR"
+if [[ -n "$BATS_TEMPDIR_CLEANUP" ]]; then
+  trap 'rm -rf "$BATS_RUN_TMPDIR"' ERR EXIT
+fi
+
+if [[ "$formatter" != "tap" ]]; then
+  flags+=('-x')
+fi
+
+if [[ -n "$report_formatter" && "$report_formatter" != "tap" ]]; then
+  flags+=('-x')
+fi
+
+if [[ "$formatter" == "junit" ]]; then
+  flags+=('-T')
+  formatter_flags+=('--base-path' "${arguments[0]}")
+fi
+if [[ "$report_formatter" == "junit" ]]; then
+  flags+=('-T')
+  report_formatter_flags+=('--base-path' "${arguments[0]}")
+fi
+
+# if we don't need to filter extended syntax, use the faster formatter
+if [[ "$formatter" == tap && -z "$report_formatter" ]]; then
+  formatter="cat"
 fi
 
 if [[ "${#arguments[@]}" -eq 0 ]]; then
   abort 'Must specify at least one <test>'
+fi
+
+if [[ -n "$report_formatter" ]]; then
+  # default to the current directory for output
+  if [[ -z "$output" ]]; then
+    output=.
+  fi
+  case "$report_formatter" in
+    tap|tap13)
+      BATS_REPORT_FILE_NAME="report.tap"
+      ;;
+    junit)
+      BATS_REPORT_FILE_NAME="report.xml"
+      ;;
+    pretty)
+      BATS_REPORT_FILE_NAME="report.log"
+      ;;
+  esac
+fi
+
+if [[ -n "$output" ]]; then
+  if [[ ! -w "${output}" ]]; then
+    abort "Output path ${output} is not writeable"
+  fi
+  export BATS_REPORT_OUTPUT_PATH="$output"
 fi
 
 filenames=()
@@ -128,31 +269,26 @@ for filename in "${arguments[@]}"; do
     shopt -s nullglob
     if [[ "$recursive" -eq 1 ]]; then
       while IFS= read -r -d $'\0' file; do
-        filenames["${#filenames[@]}"]="$file"
-      done < <(find "$filename" -type f -name "*.bats" -print0 | sort -z)
+        filenames+=("$file")
+      done < <(find -L "$filename" -type f -name "*.${BATS_FILE_EXTENSION:-bats}" -print0 | sort -z)
     else
-      for suite_filename in "$filename"/*.bats; do
-        filenames["${#filenames[@]}"]="$suite_filename"
+      for suite_filename in "$filename"/*."${BATS_FILE_EXTENSION:-bats}"; do
+        filenames+=("$suite_filename")
       done
     fi
     shopt -u nullglob
   else
-    filenames["${#filenames[@]}"]="$filename"
+    filenames+=("$filename")
   fi
 done
 
-if [[ "${#filenames[@]}" -eq 1 ]]; then
-  command="bats-exec-test"
-else
-  command="bats-exec-suite"
-fi
+# shellcheck source=lib/bats-core/validator.bash
+source "$BATS_ROOT/lib/bats-core/validator.bash"
 
 set -o pipefail execfail
-if [[ -z "$pretty" ]]; then
-  exec "$command" $count_flag "${filenames[@]}"
+
+if [[ -n "$report_formatter" ]]; then
+  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | tee >("bats-format-${report_formatter}" "${report_formatter_flags[@]}" >"${BATS_REPORT_OUTPUT_PATH}/${BATS_REPORT_FILE_NAME}") | bats_test_count_validator | "bats-format-${formatter}" "${formatter_flags[@]}"
 else
-  extended_syntax_flag="-x"
-  formatter="bats-format-tap-stream"
-  exec "$command" $count_flag $extended_syntax_flag "${filenames[@]}" |
-    "$formatter"
+  exec bats-exec-suite "${flags[@]}" "${filenames[@]}" | bats_test_count_validator | "bats-format-${formatter}" "${formatter_flags[@]}"
 fi
diff --git a/vendor/bats-core/libexec/bats-core/bats-exec-test b/vendor/bats-core/libexec/bats-core/bats-exec-test
--- a/vendor/bats-core/libexec/bats-core/bats-exec-test
+++ b/vendor/bats-core/libexec/bats-core/bats-exec-test
@@ -1,259 +1,67 @@
 #!/usr/bin/env bash
 set -eET
 
-BATS_COUNT_ONLY=""
-if [[ "$1" = "-c" ]]; then
-  BATS_COUNT_ONLY=1
-  shift
-fi
+# Variables used in other scripts.
+BATS_COUNT_ONLY=''
+BATS_TEST_FILTER=''
+BATS_ENABLE_TIMING=''
+BATS_EXTENDED_SYNTAX=''
 
-BATS_EXTENDED_SYNTAX=""
-if [[ "$1" = "-x" ]]; then
-  BATS_EXTENDED_SYNTAX="$1"
+while [[ "$#" -ne 0 ]]; do
+  case "$1" in
+  -c)
+    # shellcheck disable=SC2034
+    BATS_COUNT_ONLY=1
+    ;;
+  -f)
+    shift
+    # shellcheck disable=SC2034
+    BATS_TEST_FILTER="$1"
+    ;;
+  -T)
+    BATS_ENABLE_TIMING='-T'
+    BATS_PERFORM_TEST_CMD+=('-T')
+    ;;
+  -x)
+    # shellcheck disable=SC2034
+    BATS_EXTENDED_SYNTAX='-x'
+    ;;
+  *)
+    break
+    ;;
+  esac
   shift
-fi
+done
 
 BATS_TEST_FILENAME="$1"
+shift
 if [[ -z "$BATS_TEST_FILENAME" ]]; then
   printf 'usage: bats-exec-test <filename>\n' >&2
   exit 1
 elif [[ ! -f "$BATS_TEST_FILENAME" ]]; then
   printf 'bats: %s does not exist\n' "$BATS_TEST_FILENAME" >&2
   exit 1
-else
-  shift
 fi
 
-BATS_TEST_DIRNAME="${BATS_TEST_FILENAME%/*}"
-BATS_TEST_NAMES=()
-
-load() {
-  local name="$1"
-  local filename
-
-  if [[ "${name:0:1}" = "/" ]]; then
-    filename="${name}"
-  else
-    filename="$BATS_TEST_DIRNAME/${name}.bash"
-  fi
-
-  if [[ ! -f "$filename" ]]; then
-    printf 'bats: %s does not exist\n' "$filename" >&2
-    exit 1
-  fi
-
-  source "${filename}"
-}
-
-run() {
-  local origFlags="$-"
-  set +eET
-  local origIFS="$IFS"
-  output="$("$@" 2>&1)"
-  status="$?"
-  IFS=$'\n' lines=($output)
-  IFS="$origIFS"
-  set "-$origFlags"
-}
-
-setup() {
-  return 0
-}
-
-teardown() {
-  return 0
-}
-
-BATS_TEST_SKIPPED=''
-skip() {
-  BATS_TEST_SKIPPED="${1:-1}"
-  BATS_TEST_COMPLETED=1
-  exit 0
-}
-
-bats_test_begin() {
-  BATS_TEST_DESCRIPTION="$1"
-  if [[ -n "$BATS_EXTENDED_SYNTAX" ]]; then
-    printf 'begin %d %s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" >&3
-  fi
-  setup
-}
-
-bats_test_function() {
-  local test_name="$1"
-  BATS_TEST_NAMES+=("$test_name")
-}
-
-BATS_CURRENT_STACK_TRACE=()
-BATS_PREVIOUS_STACK_TRACE=()
-BATS_ERROR_STACK_TRACE=()
-
-bats_capture_stack_trace() {
-  if [[ "${#BATS_CURRENT_STACK_TRACE[@]}" -ne 0 ]]; then
-    BATS_PREVIOUS_STACK_TRACE=("${BATS_CURRENT_STACK_TRACE[@]}")
-  fi
-  BATS_CURRENT_STACK_TRACE=()
-
-  local test_pattern=" $BATS_TEST_NAME $BATS_TEST_SOURCE"
-  local setup_pattern=" setup $BATS_TEST_SOURCE"
-  local teardown_pattern=" teardown $BATS_TEST_SOURCE"
-
-  local source_file
-  local frame
-  local i
-
-  for ((i=2; i != ${#FUNCNAME[@]}; ++i)); do
-    # Use BATS_TEST_SOURCE if necessary to work around Bash < 4.4 bug whereby
-    # calling an exported function erases the test file's BASH_SOURCE entry.
-    source_file="${BASH_SOURCE[$i]:-$BATS_TEST_SOURCE}"
-    frame="${BASH_LINENO[$((i-1))]} ${FUNCNAME[$i]} $source_file"
-    BATS_CURRENT_STACK_TRACE["${#BATS_CURRENT_STACK_TRACE[@]}"]="$frame"
-    if [[ "$frame" = *"$test_pattern"     || \
-          "$frame" = *"$setup_pattern"    || \
-          "$frame" = *"$teardown_pattern" ]]; then
-      break
-    fi
-  done
-
-  bats_frame_filename "${BATS_CURRENT_STACK_TRACE[0]}" 'BATS_SOURCE'
-  bats_frame_lineno "${BATS_CURRENT_STACK_TRACE[0]}" 'BATS_LINENO'
-}
-
-bats_print_stack_trace() {
-  local frame
-  local index=1
-  local count="${#@}"
-  local filename
-  local lineno
-
-  for frame in "$@"; do
-    bats_frame_filename "$frame" 'filename'
-    bats_trim_filename "$filename" 'filename'
-    bats_frame_lineno "$frame" 'lineno'
-
-    if [[ $index -eq 1 ]]; then
-      printf '# ('
-    else
-      printf '#  '
-    fi
-
-    local fn
-    bats_frame_function "$frame" 'fn'
-    if [[ "$fn" != "$BATS_TEST_NAME" ]]; then
-      printf "from function \`%s' " "$fn"
-    fi
-
-    if [[ $index -eq $count ]]; then
-      printf 'in test file %s, line %d)\n' "$filename" "$lineno"
-    else
-      printf 'in file %s, line %d,\n' "$filename" "$lineno"
-    fi
-
-    let index+=1
-  done
-}
-
-bats_print_failed_command() {
-  local frame="$1"
-  local status="$2"
-  local filename
-  local lineno
-  local failed_line
-  local failed_command
-
-  bats_frame_filename "$frame" 'filename'
-  bats_frame_lineno "$frame" 'lineno'
-  bats_extract_line "$filename" "$lineno" 'failed_line'
-  bats_strip_string "$failed_line" 'failed_command'
-  printf '%s' "#   \`${failed_command}' "
-
-  if [[ $status -eq 1 ]]; then
-    printf 'failed\n'
-  else
-    printf 'failed with status %d\n' "$status"
-  fi
-}
-
-bats_frame_lineno() {
-  printf -v "$2" '%s' "${1%% *}"
-}
-
-bats_frame_function() {
-  local __bff_function="${1#* }"
-  printf -v "$2" '%s' "${__bff_function%% *}"
-}
-
-bats_frame_filename() {
-  local __bff_filename="${1#* }"
-  __bff_filename="${__bff_filename#* }"
-
-  if [[ "$__bff_filename" = "$BATS_TEST_SOURCE" ]]; then
-    __bff_filename="$BATS_TEST_FILENAME"
-  fi
-  printf -v "$2" '%s' "$__bff_filename"
-}
-
-bats_extract_line() {
-  local __bats_extract_line_line
-  local __bats_extract_line_index=0
-
-  while IFS= read -r __bats_extract_line_line; do
-    if [[ "$((++__bats_extract_line_index))" -eq "$2" ]]; then
-      printf -v "$3" '%s' "${__bats_extract_line_line%$'\r'}"
-      break
-    fi
-  done <"$1"
-}
-
-bats_strip_string() {
-  [[ "$1" =~ ^[[:space:]]*(.*)[[:space:]]*$ ]]
-  printf -v "$2" '%s' "${BASH_REMATCH[1]}"
-}
-
-bats_trim_filename() {
-  printf -v "$2" '%s' "${1#$BATS_CWD/}"
-}
-
-bats_debug_trap() {
-  if [[ "$BASH_SOURCE" != "$1" ]]; then
-    bats_capture_stack_trace
-  fi
-}
-
-# For some versions of Bash, the `ERR` trap may not always fire for every
-# command failure, but the `EXIT` trap will. Also, some command failures may not
-# set `$?` properly. See #72 and #81 for details.
-#
-# For this reason, we call `bats_error_trap` at the very beginning of
-# `bats_teardown_trap` (the `DEBUG` trap for the call will move
-# `BATS_CURRENT_STACK_TRACE` to `BATS_PREVIOUS_STACK_TRACE`) and check the value
-# of `$BATS_TEST_COMPLETED` before taking other actions. We also adjust the exit
-# status value if needed.
-#
-# See `bats_exit_trap` for an additional EXIT error handling case when `$?`
-# isn't set properly during `teardown()` errors.
-bats_error_trap() {
-  local status="$?"
-  if [[ -z "$BATS_TEST_COMPLETED" ]]; then
-    BATS_ERROR_STATUS="${BATS_ERROR_STATUS:-$status}"
-    if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
-      BATS_ERROR_STATUS=1
-    fi
-    BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
-    trap - debug
-  fi
-}
+# load the test helper functions like `load` or `run` that are needed to run a (preprocessed) .bats file without bash errors
+# shellcheck source=lib/bats-core/test_functions.bash disable=SC2153
+source "$BATS_ROOT/lib/bats-core/test_functions.bash"
+# shellcheck source=lib/bats-core/tracing.bash disable=SC2153
+source "$BATS_ROOT/lib/bats-core/tracing.bash"
 
 bats_teardown_trap() {
   bats_error_trap
   local status=0
+  # mark the start of this function to distinguish where skip is called
+  # parameter 1 will signify the reason why this function was called
+  # this is used to identify when this is called as exit trap function
+  BATS_TEARDOWN_STARTED=${1:-1}
   teardown >>"$BATS_OUT" 2>&1 || status="$?"
 
   if [[ $status -eq 0 ]]; then
     BATS_TEARDOWN_COMPLETED=1
   elif [[ -n "$BATS_TEST_COMPLETED" ]]; then
     BATS_ERROR_STATUS="$status"
-    BATS_ERROR_STACK_TRACE=( "${BATS_CURRENT_STACK_TRACE[@]}" )
   fi
 
   bats_exit_trap
@@ -263,17 +71,22 @@ bats_exit_trap() {
   local line
   local status
   local skipped=''
-  trap - err exit
+  trap - ERR EXIT
 
   if [[ -n "$BATS_TEST_SKIPPED" ]]; then
-    skipped=" # skip"
+    skipped=' # skip'
     if [[ "$BATS_TEST_SKIPPED" != '1' ]]; then
       skipped+=" $BATS_TEST_SKIPPED"
     fi
   fi
 
+  BATS_TEST_TIME=''
+  if [[ -z "${skipped}" && -n "$BATS_ENABLE_TIMING" ]]; then
+    BATS_TEST_TIME=" in "$(( $(get_mills_since_epoch) - BATS_TEST_START_TIME ))"ms"
+  fi
+
   if [[ -z "$BATS_TEST_COMPLETED" || -z "$BATS_TEARDOWN_COMPLETED" ]]; then
-    if [[ "${#BATS_ERROR_STACK_TRACE[@]}" -eq 0 ]]; then
+    if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
       # For some versions of bash, `$?` may not be set properly for some error
       # conditions before triggering the EXIT trap directly (see #72 and #81).
       # Thanks to the `BATS_TEARDOWN_COMPLETED` signal, this will pinpoint such
@@ -283,24 +96,22 @@ bats_exit_trap() {
       # If instead the test fails, and the `teardown()` error happens while
       # `bats_teardown_trap` runs as the EXIT trap, the test will fail with no
       # output, since there's no way to reach the `bats_exit_trap` call.
-      BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
+      BATS_STACK_TRACE=("${BATS_CURRENT_STACK_TRACE[@]}")
       BATS_ERROR_STATUS=1
     fi
-    printf 'not ok %d %s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" >&3
-    bats_print_stack_trace "${BATS_ERROR_STACK_TRACE[@]}" >&3
-    bats_print_failed_command \
-      "${BATS_ERROR_STACK_TRACE[${#BATS_ERROR_STACK_TRACE[@]}-1]}" \
-      "$BATS_ERROR_STATUS" >&3
+    printf 'not ok %d %s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" >&3
+    bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
+    bats_print_failed_command >&3
 
     while IFS= read -r line; do
-      printf '# %s\n' "$line"
+      printf '# %s\n' "$line" || break # avoid feedback loop when errors are redirected into BATS_OUT (see #353)
     done <"$BATS_OUT" >&3
     if [[ -n "$line" ]]; then
       printf '# %s\n' "$line"
     fi
     status=1
   else
-    printf 'ok %d %s%s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" \
+    printf 'ok %d %s%s\n' "$BATS_SUITE_TEST_NUMBER" "${BATS_TEST_DESCRIPTION}${BATS_TEST_TIME}" \
       "$skipped" >&3
     status=0
   fi
@@ -309,113 +120,60 @@ bats_exit_trap() {
   exit "$status"
 }
 
-bats_perform_tests() {
-  printf '1..%d\n' "$#"
-  test_number=1
-  status=0
-  for test_name in "$@"; do
-    if ! "$0" $BATS_EXTENDED_SYNTAX "$BATS_TEST_FILENAME" "$test_name" \
-      "$test_number"; then
-      status=1
-    fi
-    let test_number+=1
-  done
-  exit "$status"
+get_mills_since_epoch() {
+  local ms_since_epoch
+  ms_since_epoch=$(date +%s%N)
+  if [[ "$ms_since_epoch" == *N || "${#ms_since_epoch}" -lt 19 ]]; then
+        ms_since_epoch=$(( $(date +%s) * 1000 ))
+  else
+        ms_since_epoch=$(( ms_since_epoch / 1000000 ))
+  fi
+
+  printf "%d\n" "$ms_since_epoch"
 }
 
 bats_perform_test() {
-  BATS_TEST_NAME="$1"
-  if declare -F "$BATS_TEST_NAME" >/dev/null; then
-    BATS_TEST_NUMBER="$2"
-    if [[ -z "$BATS_TEST_NUMBER" ]]; then
-      printf '1..1\n'
-      BATS_TEST_NUMBER=1
-    fi
+  export BATS_TEST_NAME="$1"
+  export BATS_SUITE_TEST_NUMBER="$2"
+  export BATS_TEST_NUMBER="$3"
 
-    BATS_TEST_COMPLETED=""
-    BATS_TEARDOWN_COMPLETED=""
-    BATS_ERROR_STATUS=""
-    trap "bats_debug_trap \"\$BASH_SOURCE\"" debug
-    trap "bats_error_trap" err
-    trap "bats_teardown_trap" exit
-    "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
-    BATS_TEST_COMPLETED=1
-    trap "bats_exit_trap" exit
-    bats_teardown_trap
-
-  else
+  if ! declare -F "$BATS_TEST_NAME" &>/dev/null; then
     printf "bats: unknown test name \`%s'\n" "$BATS_TEST_NAME" >&2
     exit 1
   fi
+
+  # Some versions of Bash will reset BASH_LINENO to the first line of the
+  # function when the ERR trap fires. All versions of Bash appear to reset it
+  # on an unbound variable access error. bats_debug_trap will fire both before
+  # the offending line is executed, and when the error is triggered.
+  # Consequently, we use `BATS_CURRENT_STACK_TRACE` recorded by the
+  # first call to bats_debug_trap, _before_ the ERR trap or unbound variable
+  # access fires.
+  BATS_STACK_TRACE=()
+  BATS_CURRENT_STACK_TRACE=()
+
+  BATS_TEST_COMPLETED=
+  BATS_TEST_SKIPPED=
+  BATS_TEARDOWN_COMPLETED=
+  BATS_ERROR_STATUS=
+  trap 'bats_debug_trap "$BASH_SOURCE"' DEBUG
+  trap 'bats_error_trap' ERR
+  # mark this call as trap call
+  trap 'bats_teardown_trap as-exit-trap' EXIT
+
+  BATS_TEST_START_TIME=$(get_mills_since_epoch)
+  "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
+
+  BATS_TEST_COMPLETED=1
+  trap 'bats_exit_trap' EXIT
+  bats_teardown_trap "" # pass empty parameter to signify call outside trap
 }
 
-if [[ -z "$TMPDIR" ]]; then
-  BATS_TMPDIR="/tmp"
-else
-  BATS_TMPDIR="${TMPDIR%/}"
-fi
-
-BATS_TMPNAME="$BATS_TMPDIR/bats.$$"
-BATS_PARENT_TMPNAME="$BATS_TMPDIR/bats.$PPID"
-BATS_OUT="${BATS_TMPNAME}.out"
-
-bats_preprocess_source() {
-  BATS_TEST_SOURCE="${BATS_TMPNAME}.src"
-  . bats-preprocess <<< "$(< "$BATS_TEST_FILENAME")"$'\n' > "$BATS_TEST_SOURCE"
-  trap "bats_cleanup_preprocessed_source" err exit
-  trap "bats_cleanup_preprocessed_source; exit 1" int
-
-  bats_detect_duplicate_test_case_names
-}
-
-bats_cleanup_preprocessed_source() {
-  rm -f "$BATS_TEST_SOURCE"
-}
-
-bats_detect_duplicate_test_case_names() {
-  local test_names=()
-  local test_dupes=()
-  local line
-
-  while read -r line; do
-    if [[ ! "$line" =~ ^bats_test_function\  ]]; then
-      continue
-    fi
-    line="${line%$'\r'}"
-    line="${line#* }"
-
-    if [[ " ${test_names[*]} " == *" $line "* ]]; then
-      test_dupes+=("$line")
-      continue
-    fi
-    test_names+=("$line")
-  done <"$BATS_TEST_SOURCE"
-
-  if [[ "${#test_dupes[@]}" -ne 0 ]]; then
-    printf 'bats warning: duplicate test name(s) in %s: %s\n' \
-      "$BATS_TEST_FILENAME" "${test_dupes[*]}" >&2
-  fi
-}
-
-bats_evaluate_preprocessed_source() {
-  if [[ -z "$BATS_TEST_SOURCE" ]]; then
-    BATS_TEST_SOURCE="${BATS_PARENT_TMPNAME}.src"
-  fi
-  source "$BATS_TEST_SOURCE"
-}
+# shellcheck source=lib/bats-core/preprocessing.bash
+source "$BATS_ROOT/lib/bats-core/preprocessing.bash"
 
 exec 3<&1
 
-if [[ "$#" -eq 0 ]]; then
-  bats_preprocess_source
-  bats_evaluate_preprocessed_source
-
-  if [[ -n "$BATS_COUNT_ONLY" ]]; then
-    printf '%d\n' "${#BATS_TEST_NAMES[@]}"
-  else
-    bats_perform_tests "${BATS_TEST_NAMES[@]}"
-  fi
-else
-  bats_evaluate_preprocessed_source
-  bats_perform_test "$@"
-fi
+# Run the given test.
+bats_evaluate_preprocessed_source
+bats_perform_test "$@"
