Revert "upgrade bats-core to dev version  8789f91"
This reverts commit ca52f220b7117453d4c7c55e7ee1cf848bcca636.

diff --git a/vendor/bats-core/libexec/bats-core/bats-exec-test b/vendor/bats-core/libexec/bats-core/bats-exec-test
--- a/vendor/bats-core/libexec/bats-core/bats-exec-test
+++ b/vendor/bats-core/libexec/bats-core/bats-exec-test
@@ -1,37 +1,27 @@
 #!/usr/bin/env bash
 set -eET
 
-BATS_COUNT_ONLY=''
-BATS_TEST_FILTER=''
-BATS_EXTENDED_SYNTAX=''
-
-while [[ "$#" -ne 0 ]]; do
-  case "$1" in
-  -c)
-    BATS_COUNT_ONLY=1
-    ;;
-  -f)
-    shift
-    BATS_TEST_FILTER="$1"
-    ;;
-  -x)
-    BATS_EXTENDED_SYNTAX='-x'
-    ;;
-  *)
-    break
-    ;;
-  esac
+BATS_COUNT_ONLY=""
+if [[ "$1" = "-c" ]]; then
+  BATS_COUNT_ONLY=1
   shift
-done
+fi
+
+BATS_EXTENDED_SYNTAX=""
+if [[ "$1" = "-x" ]]; then
+  BATS_EXTENDED_SYNTAX="$1"
+  shift
+fi
 
 BATS_TEST_FILENAME="$1"
-shift
 if [[ -z "$BATS_TEST_FILENAME" ]]; then
   printf 'usage: bats-exec-test <filename>\n' >&2
   exit 1
 elif [[ ! -f "$BATS_TEST_FILENAME" ]]; then
   printf 'bats: %s does not exist\n' "$BATS_TEST_FILENAME" >&2
   exit 1
+else
+  shift
 fi
 
 BATS_TEST_DIRNAME="${BATS_TEST_FILENAME%/*}"
@@ -41,7 +31,7 @@ load() {
   local name="$1"
   local filename
 
-  if [[ "${name:0:1}" == '/' ]]; then
+  if [[ "${name:0:1}" = "/" ]]; then
     filename="${name}"
   else
     filename="$BATS_TEST_DIRNAME/${name}.bash"
@@ -74,6 +64,7 @@ teardown() {
   return 0
 }
 
+BATS_TEST_SKIPPED=''
 skip() {
   BATS_TEST_SKIPPED="${1:-1}"
   BATS_TEST_COMPLETED=1
@@ -93,27 +84,39 @@ bats_test_function() {
   BATS_TEST_NAMES+=("$test_name")
 }
 
-bats_capture_stack_trace() {
-  local test_file
-  local funcname
-  local i
+BATS_CURRENT_STACK_TRACE=()
+BATS_PREVIOUS_STACK_TRACE=()
+BATS_ERROR_STACK_TRACE=()
 
-  BATS_STACK_TRACE=()
+bats_capture_stack_trace() {
+  if [[ "${#BATS_CURRENT_STACK_TRACE[@]}" -ne 0 ]]; then
+    BATS_PREVIOUS_STACK_TRACE=("${BATS_CURRENT_STACK_TRACE[@]}")
+  fi
+  BATS_CURRENT_STACK_TRACE=()
+
+  local test_pattern=" $BATS_TEST_NAME $BATS_TEST_SOURCE"
+  local setup_pattern=" setup $BATS_TEST_SOURCE"
+  local teardown_pattern=" teardown $BATS_TEST_SOURCE"
+
+  local source_file
+  local frame
+  local i
 
   for ((i=2; i != ${#FUNCNAME[@]}; ++i)); do
     # Use BATS_TEST_SOURCE if necessary to work around Bash < 4.4 bug whereby
     # calling an exported function erases the test file's BASH_SOURCE entry.
-    test_file="${BASH_SOURCE[$i]:-$BATS_TEST_SOURCE}"
-    funcname="${FUNCNAME[$i]}"
-    BATS_STACK_TRACE+=("${BASH_LINENO[$((i-1))]} $funcname $test_file")
-    if [[ "$test_file" == "$BATS_TEST_SOURCE" ]]; then
-      case "$funcname" in
-      "$BATS_TEST_NAME"|setup|teardown)
-        break
-        ;;
-      esac
+    source_file="${BASH_SOURCE[$i]:-$BATS_TEST_SOURCE}"
+    frame="${BASH_LINENO[$((i-1))]} ${FUNCNAME[$i]} $source_file"
+    BATS_CURRENT_STACK_TRACE["${#BATS_CURRENT_STACK_TRACE[@]}"]="$frame"
+    if [[ "$frame" = *"$test_pattern"     || \
+          "$frame" = *"$setup_pattern"    || \
+          "$frame" = *"$teardown_pattern" ]]; then
+      break
     fi
   done
+
+  bats_frame_filename "${BATS_CURRENT_STACK_TRACE[0]}" 'BATS_SOURCE'
+  bats_frame_lineno "${BATS_CURRENT_STACK_TRACE[0]}" 'BATS_LINENO'
 }
 
 bats_print_stack_trace() {
@@ -146,12 +149,13 @@ bats_print_stack_trace() {
       printf 'in file %s, line %d,\n' "$filename" "$lineno"
     fi
 
-    ((++index))
+    let index+=1
   done
 }
 
 bats_print_failed_command() {
-  local frame="${BATS_STACK_TRACE[${#BATS_STACK_TRACE[@]}-1]}"
+  local frame="$1"
+  local status="$2"
   local filename
   local lineno
   local failed_line
@@ -163,10 +167,10 @@ bats_print_failed_command() {
   bats_strip_string "$failed_line" 'failed_command'
   printf '%s' "#   \`${failed_command}' "
 
-  if [[ "$BATS_ERROR_STATUS" -eq 1 ]]; then
+  if [[ $status -eq 1 ]]; then
     printf 'failed\n'
   else
-    printf 'failed with status %d\n' "$BATS_ERROR_STATUS"
+    printf 'failed with status %d\n' "$status"
   fi
 }
 
@@ -183,7 +187,7 @@ bats_frame_filename() {
   local __bff_filename="${1#* }"
   __bff_filename="${__bff_filename#* }"
 
-  if [[ "$__bff_filename" == "$BATS_TEST_SOURCE" ]]; then
+  if [[ "$__bff_filename" = "$BATS_TEST_SOURCE" ]]; then
     __bff_filename="$BATS_TEST_FILENAME"
   fi
   printf -v "$2" '%s' "$__bff_filename"
@@ -213,8 +217,6 @@ bats_trim_filename() {
 bats_debug_trap() {
   if [[ "$BASH_SOURCE" != "$1" ]]; then
     bats_capture_stack_trace
-    BATS_LINENO="$BATS_CURRENT_LINENO"
-    BATS_CURRENT_LINENO="${BASH_LINENO[0]}"
   fi
 }
 
@@ -224,8 +226,8 @@ bats_debug_trap() {
 #
 # For this reason, we call `bats_error_trap` at the very beginning of
 # `bats_teardown_trap` (the `DEBUG` trap for the call will move
-# `BATS_CURRENT_LINENO` to `BATS_LINENO`) and check the value of
-# `$BATS_TEST_COMPLETED` before taking other actions. We also adjust the exit
+# `BATS_CURRENT_STACK_TRACE` to `BATS_PREVIOUS_STACK_TRACE`) and check the value
+# of `$BATS_TEST_COMPLETED` before taking other actions. We also adjust the exit
 # status value if needed.
 #
 # See `bats_exit_trap` for an additional EXIT error handling case when `$?`
@@ -237,7 +239,7 @@ bats_error_trap() {
     if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
       BATS_ERROR_STATUS=1
     fi
-    BATS_STACK_TRACE[0]="$BATS_LINENO ${BATS_STACK_TRACE[0]#* }"
+    BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
     trap - debug
   fi
 }
@@ -251,6 +253,7 @@ bats_teardown_trap() {
     BATS_TEARDOWN_COMPLETED=1
   elif [[ -n "$BATS_TEST_COMPLETED" ]]; then
     BATS_ERROR_STATUS="$status"
+    BATS_ERROR_STACK_TRACE=( "${BATS_CURRENT_STACK_TRACE[@]}" )
   fi
 
   bats_exit_trap
@@ -263,14 +266,14 @@ bats_exit_trap() {
   trap - err exit
 
   if [[ -n "$BATS_TEST_SKIPPED" ]]; then
-    skipped=' # skip'
+    skipped=" # skip"
     if [[ "$BATS_TEST_SKIPPED" != '1' ]]; then
       skipped+=" $BATS_TEST_SKIPPED"
     fi
   fi
 
   if [[ -z "$BATS_TEST_COMPLETED" || -z "$BATS_TEARDOWN_COMPLETED" ]]; then
-    if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
+    if [[ "${#BATS_ERROR_STACK_TRACE[@]}" -eq 0 ]]; then
       # For some versions of bash, `$?` may not be set properly for some error
       # conditions before triggering the EXIT trap directly (see #72 and #81).
       # Thanks to the `BATS_TEARDOWN_COMPLETED` signal, this will pinpoint such
@@ -280,12 +283,14 @@ bats_exit_trap() {
       # If instead the test fails, and the `teardown()` error happens while
       # `bats_teardown_trap` runs as the EXIT trap, the test will fail with no
       # output, since there's no way to reach the `bats_exit_trap` call.
-      BATS_STACK_TRACE[0]="$BATS_LINENO ${BATS_STACK_TRACE[0]#* }"
+      BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
       BATS_ERROR_STATUS=1
     fi
     printf 'not ok %d %s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" >&3
-    bats_print_stack_trace "${BATS_STACK_TRACE[@]}" >&3
-    bats_print_failed_command >&3
+    bats_print_stack_trace "${BATS_ERROR_STACK_TRACE[@]}" >&3
+    bats_print_failed_command \
+      "${BATS_ERROR_STACK_TRACE[${#BATS_ERROR_STACK_TRACE[@]}-1]}" \
+      "$BATS_ERROR_STATUS" >&3
 
     while IFS= read -r line; do
       printf '# %s\n' "$line"
@@ -304,41 +309,48 @@ bats_exit_trap() {
   exit "$status"
 }
 
+bats_perform_tests() {
+  printf '1..%d\n' "$#"
+  test_number=1
+  status=0
+  for test_name in "$@"; do
+    if ! "$0" $BATS_EXTENDED_SYNTAX "$BATS_TEST_FILENAME" "$test_name" \
+      "$test_number"; then
+      status=1
+    fi
+    let test_number+=1
+  done
+  exit "$status"
+}
+
 bats_perform_test() {
   BATS_TEST_NAME="$1"
-  BATS_TEST_NUMBER="$2"
+  if declare -F "$BATS_TEST_NAME" >/dev/null; then
+    BATS_TEST_NUMBER="$2"
+    if [[ -z "$BATS_TEST_NUMBER" ]]; then
+      printf '1..1\n'
+      BATS_TEST_NUMBER=1
+    fi
 
-  if ! declare -F "$BATS_TEST_NAME" &>/dev/null; then
+    BATS_TEST_COMPLETED=""
+    BATS_TEARDOWN_COMPLETED=""
+    BATS_ERROR_STATUS=""
+    trap "bats_debug_trap \"\$BASH_SOURCE\"" debug
+    trap "bats_error_trap" err
+    trap "bats_teardown_trap" exit
+    "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
+    BATS_TEST_COMPLETED=1
+    trap "bats_exit_trap" exit
+    bats_teardown_trap
+
+  else
     printf "bats: unknown test name \`%s'\n" "$BATS_TEST_NAME" >&2
     exit 1
   fi
-
-  # Some versions of Bash will reset BASH_LINENO to the first line of the
-  # function when the ERR trap fires. All versions of Bash appear to reset it
-  # on an unbound variable access error. bats_debug_trap will fire both before
-  # the offending line is executed, and when the error is triggered.
-  # Consequently, we use `BATS_LINENO` to point to the line number seen by the
-  # first call to bats_debug_trap, _before_ the ERR trap or unbound variable
-  # access fires.
-  BATS_CURRENT_LINENO=0
-  BATS_LINENO=0
-  BATS_STACK_TRACE=()
-
-  BATS_TEST_COMPLETED=
-  BATS_TEST_SKIPPED=
-  BATS_TEARDOWN_COMPLETED=
-  BATS_ERROR_STATUS=
-  trap "bats_debug_trap \"\$BASH_SOURCE\"" debug
-  trap 'bats_error_trap' err
-  trap 'bats_teardown_trap' exit
-  "$BATS_TEST_NAME" >>"$BATS_OUT" 2>&1
-  BATS_TEST_COMPLETED=1
-  trap 'bats_exit_trap' exit
-  bats_teardown_trap
 }
 
 if [[ -z "$TMPDIR" ]]; then
-  BATS_TMPDIR='/tmp'
+  BATS_TMPDIR="/tmp"
 else
   BATS_TMPDIR="${TMPDIR%/}"
 fi
@@ -349,13 +361,40 @@ BATS_OUT="${BATS_TMPNAME}.out"
 
 bats_preprocess_source() {
   BATS_TEST_SOURCE="${BATS_TMPNAME}.src"
-  bats-preprocess "$BATS_TEST_FILENAME" >"$BATS_TEST_SOURCE"
-  trap 'bats_cleanup_preprocessed_source' err exit
-  trap 'bats_cleanup_preprocessed_source; exit 1' int
+  . bats-preprocess <<< "$(< "$BATS_TEST_FILENAME")"$'\n' > "$BATS_TEST_SOURCE"
+  trap "bats_cleanup_preprocessed_source" err exit
+  trap "bats_cleanup_preprocessed_source; exit 1" int
+
+  bats_detect_duplicate_test_case_names
 }
 
 bats_cleanup_preprocessed_source() {
   rm -f "$BATS_TEST_SOURCE"
+}
+
+bats_detect_duplicate_test_case_names() {
+  local test_names=()
+  local test_dupes=()
+  local line
+
+  while read -r line; do
+    if [[ ! "$line" =~ ^bats_test_function\  ]]; then
+      continue
+    fi
+    line="${line%$'\r'}"
+    line="${line#* }"
+
+    if [[ " ${test_names[*]} " == *" $line "* ]]; then
+      test_dupes+=("$line")
+      continue
+    fi
+    test_names+=("$line")
+  done <"$BATS_TEST_SOURCE"
+
+  if [[ "${#test_dupes[@]}" -ne 0 ]]; then
+    printf 'bats warning: duplicate test name(s) in %s: %s\n' \
+      "$BATS_TEST_FILENAME" "${test_dupes[*]}" >&2
+  fi
 }
 
 bats_evaluate_preprocessed_source() {
@@ -367,7 +406,16 @@ bats_evaluate_preprocessed_source() {
 
 exec 3<&1
 
-# Run the given test.
-bats_preprocess_source
-bats_evaluate_preprocessed_source
-bats_perform_test "$@"
+if [[ "$#" -eq 0 ]]; then
+  bats_preprocess_source
+  bats_evaluate_preprocessed_source
+
+  if [[ -n "$BATS_COUNT_ONLY" ]]; then
+    printf '%d\n' "${#BATS_TEST_NAMES[@]}"
+  else
+    bats_perform_tests "${BATS_TEST_NAMES[@]}"
+  fi
+else
+  bats_evaluate_preprocessed_source
+  bats_perform_test "$@"
+fi
